sudo: required
language: r
warnings_are_errors: false
env:
  global:
    - LINTR_COMMENT_BOT=true

r_packages:
- stats
- Rdpack
- testthat
- covr
- knitr
- rmarkdown
- lintr

r_github_packages:
- aae-stats/aae.pop

cache:
  packages: true
  directories:
  - "$HOME/.cache/pip"

after_success:
- Rscript -e "covr::codecov(type = 'all')"
- Rscript -e "lintr::lint_package()"

email:
  on_success: change
  on_failure: change
